#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer ParticleFluxBuffer {
  float particleFlux[];
};

layout(std430, binding = 1) writeonly buffer VelocityBuffer {
  float velocity[];
};

layout(push_constant) uniform Parameters {
  float depositionRate;
  float reactionOrder;
  uint elementCount;
} parameters;

void main() {
  const uint index = gl_GlobalInvocationID.x;
  if (index >= parameters.elementCount)
    return;
  velocity[index] = parameters.depositionRate *
                    pow(particleFlux[index], parameters.reactionOrder);
}
